service: px-hello
useDotenv: true

frameworkVersion: "4"

plugins:
  - serverless-dotenv-plugin  
  
provider:
  name: aws
  runtime: python3.11
  region: sa-east-1
  stage: dev
  memorySize: 256
  timeout: 10
  logRetentionInDays: 7
  environment:
    PX_API_KEY: ${env:PX_API_KEY}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    SUPABASE_TX_TABLE: ${env:SUPABASE_TX_TABLE, 'transactions'}
    SUPABASE_CONTACTS_TABLE: ${env:SUPABASE_CONTACTS_TABLE, 'contacts'}
    USE_SUPABASE: ${env:USE_SUPABASE, 'false'}
    DEBUG: ${env:DEBUG, 'false'}



functions:
  triageFetchLatest:
    handler: handler.triage_fetch_latest
    events:
      - http:
          path: v1/triage/fetch-latest

          method: post
          cors: true